import type { NextPage } from "next";
import Head from "next/head";
import { Footer, Header, LatestPostCard } from "components";

const Home: NextPage = () => {
  return (
    <div style={{ margin: "-8px" }}>
      <Head>
        <title>Fair Enough Trips</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <LatestPostCard />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
