import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Navbar, PostCard } from "components";
import { PostCardList } from "components/post-card-list/PostCardList";
import { Post } from "components/post-card-list/PostCardList.types";
import { mongoClient } from "MongoClient";
import Config from "Config";
import { removeSelectedProps } from "utils";

type HomePageProps = {
  mainPost: Post;
  latestPosts: Post[];
};

const Home: NextPage<HomePageProps> = ({ mainPost, latestPosts }) => {
  return (
    <div>
      <Head>
        <title>Fair Enough Trips</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <main>
        <PostCard isMainPostCard post={mainPost} />
        <PostCardList listTitle="Latest trips" posts={latestPosts} />
      </main>
      <Navbar />
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  await mongoClient.connect();

  const latestPosts = await mongoClient
    .db(Config.DB_NAME)
    .collection(Config.COLLECTION_NAME)
    .find()
    .limit(Config.POST_COUNT_HOME_PAGE + 1)
    .toArray();

  const sanitizedPosts = latestPosts.map((post) =>
    removeSelectedProps<Post>(post, ["_id"]),
  );

  return {
    props: {
      mainPost: { ...sanitizedPosts[0] } as Post,
      latestPosts: sanitizedPosts.slice(
        1,
        Config.POST_COUNT_HOME_PAGE + 1,
      ) as Post[],
    },
  };
};
