import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Footer, Header, PostCard } from "components";
import { PostCardList } from "components/post-card-list/PostCardList";
import { Post } from "components/post-card-list/PostCardList.types";
import { mongoClient } from "MongoClient";
import Config from "Config";

type HomePageProps = {
  mainPost: Post;
  latestPosts: Post[];
};

const Home: NextPage<HomePageProps> = ({ mainPost, latestPosts }) => {
  return (
    <div>
      <Head>
        <title>Fair Enough Trips</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <main>
        <PostCard isMainPostCard post={mainPost} />
        <PostCardList listTitle="Latest trips" posts={latestPosts} />
      </main>
      <Header />
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  await mongoClient.connect();

  const latestPostsCursor = mongoClient
    .db(Config.DB_NAME)
    .collection(Config.COLLECTION_NAME)
    .find()
    .limit(Config.POST_COUNT_HOME_PAGE + 1);

  const latestPosts = await latestPostsCursor.toArray();

  const sanitizedPosts = latestPosts.map((post) =>
    Object.fromEntries(
      Object.entries(post).filter((entry) => !entry.includes("_id")),
    ),
  );

  return {
    props: {
      mainPost: { ...sanitizedPosts[0] } as Post,
      latestPosts: sanitizedPosts.slice(1, 7) as Post[],
    },
  };
};
