import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Footer, Layout, Navbar, PostCard } from "components";
import CardList from "components/card-list/CardList";
import { Post } from "components/card-list/CardList.types";
import { mongoClient } from "MongoClient";
import Config from "Config";
import { CategoriesEnum, Regions } from "enums/categories";
import { CategoryCard } from "components/category-card/CategoryCard";
import { TripNote, TripNotes } from "components/trip-notes/TripNotes";
import { Box } from "components/box/Box";
import { parse } from "utils";

type HomePageProps = {
  posts: Post[];
  code: string;
  notes: TripNote[];
};

const Category: NextPage<HomePageProps> = ({ posts, code, notes }) => {
  const region = Regions.find((act) => act.code === code)!;

  return (
    <div>
      <Head>
        <title>{region.name} @ Fair Enough Trips</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <main>
        <CategoryCard
          isMainCard
          postIds={posts.map(({ id }) => id)}
          categoryType={CategoriesEnum.Regions}
          category={region}
          areNotesPresent={Boolean(notes.length)}
        />
        {Boolean(notes.length) && (
          <Layout>
            <Box margin="0 0 32px">
              <TripNotes notes={notes} />
            </Box>
          </Layout>
        )}
        {Boolean(posts.length) && (
          <CardList listTitle={`Latest trips in ${region.name}`}>
            {posts.map((post) => (
              <PostCard post={post} key={post.id} />
            ))}
          </CardList>
        )}
      </main>
      <Footer />
    </div>
  );
};

export default Category;

export const getStaticPaths: GetStaticPaths = async () => {
  await mongoClient.connect();

  const collection = mongoClient
    .db(Config.DB_NAME)
    .collection(Config.POSTS_COLLECTION);

  const posts = await collection.find().toArray();
  await mongoClient.close();

  const types = Array.from(
    new Set(posts.map(({ category }) => category.region).flat())
  )
    .map((code) => Regions.find((act) => act.code === code)?.url)
    .map((path) => ({ params: { region: path } }));
  return {
    paths: types,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  await mongoClient.connect();

  const code = Regions.find((act) => act.url === params?.region)?.code;

  const posts = await mongoClient
    .db(Config.DB_NAME)
    .collection(Config.POSTS_COLLECTION)
    .find({ ["category.region"]: code })
    .sort({ postDate: -1 })
    .toArray();

  const notes = await mongoClient
    .db(Config.DB_NAME)
    .collection(Config.REGION_NOTES_COLLECTION)
    .findOne({ id: code });

  await mongoClient.close();

  const postsParsed = parse(posts);
  const notesParsed = parse(notes);

  return {
    props: {
      posts: postsParsed,
      code,
      notes: notesParsed?.notes ?? [],
    },
  };
};
