export default {
  DEFAULT_IMAGE_EXTENSION: "webp",
  COMPRESSED_FILE_EXTENSION: "zip",
  IMAGE_STRETCH_S: 600,
  IMAGE_STRETCH_M: 800,
  IMAGE_STRETCH_L: 1066,
  DB_NAME: "fet",
  POSTS_COLLECTION: "posts-test",
  POST_COUNT_HOME_PAGE: 6,
  MAX_STARS_COUNT: 5,
  REGION_NOTES_COLLECTION: "region-trip-notes",
  COUNTRY_NOTES_COLLECTION: "country-trip-notes",
  EXTERNAL_MAP_TIMEOUT: 20000,
  THUMBNAIL_PREFIX_MOBILE: "thumb_",
  ROUTE_SCHEME_POINTS: "route-scheme-points",
  DOMAIN: "fairenoughtrips.com",
  S3_BUCKET: "https://fair-enough-trips.s3.eu-central-1.amazonaws.com",
};
