export default {
  DEFAULT_IMAGE_EXTENSION: "webp",
  COMPRESSED_FILE_EXTENSION: "zip",
  LONG_STRETCH: 1066,
  SHORT_STRETCH: 800,
  DB_NAME: "fet",
  COLLECTION_NAME: "posts",
  POST_COUNT_HOME_PAGE: 6,
};
