export default {
  DEFAULT_IMAGE_EXTENSION: "webp",
  COMPRESSED_FILE_EXTENSION: "zip",
  LONG_STRETCH: 1066,
  SHORT_STRETCH: 800,
  DB_NAME: "fet",
  POSTS_COLLECTION: "posts-test",
  POST_COUNT_HOME_PAGE: 6,
  MAX_STARS_COUNT: 5,
  REGION_NOTES_COLLECTION: "region-trip-notes",
  COUNTRY_NOTES_COLLECTION: "country-trip-notes",
};
